### ISSUE TITLE
Návod na lokální nasazení VL je nepřesný

### ISSUE THREAD

**Issue by bindeali** [opendata-mvcr/sgov-assembly-line#92]
# Popis problému
Readme tohoto git repozitáře je pro nasazení lokálně nedostatečné. Přesné nedostatky:

> V al-db-serveru (/modelujeme/sluzby/al-db-serveru) importujte do repozitáře všechny soubory v sekci Server files do kontextu 'http://onto.fel.cvut.cz/ontologies/termit'. Rovněž spusťe SPARQL dotazy ve složce lucene.
> V al-auth-serveru (/modelujeme/sluzby/al-auth-server, přihlas se do něj pomocí $KEYCLOAK_USER a $KEYCLOAK_PASSWORD)

Zde by měly dané URL být `/modelujeme/sluzby/db-server` a `/modelujeme/sluzby/auth-server`.

> Ověř, že Výrobní linka běží. V případě lokálního nasazení je její URL http://localhost/modelujeme.

http://localhost:1234/modelujeme

To jsou ale drobnosti, největší problém mám při nastavování Keycloaku, kdy se nejde dostat k příhlášení jako admin. 
- Kliknutí na přihlášení na http://localhost:1234/modelujeme/sluzby/auth-server/ se dostanu na https://xn--slovnk-7va.dev/modelujeme/sluzby/auth-server/admin/ - 404. 
- Úprava adresy na http://localhost:1234/modelujeme/sluzby/auth-server/admin má stejný výsledek.
- http://localhost:1234/modelujeme/sluzby/auth-server/admin/master/console/ je prázdná obrazovka s chybou:

`GET https://xn--slovnk-7va.dev/modelujeme/sluzby/auth-server/js/keycloak.js?version=9ds4a net::ERR_NAME_NOT_RESOLVED`

`jquery.min.js:2 jQuery.Deferred exception: Keycloak is not defined ReferenceError: Keycloak is not defined
    at HTMLDocument.<anonymous> (http://localhost:1234/modelujeme/sluzby/auth-server/resources/9ds4a/admin/keycloak/js/app.js:14:24)
    at e (http://localhost:1234/modelujeme/sluzby/auth-server/resources/9ds4a/common/keycloak/node_modules/jquery/dist/jquery.min.js:2:30005)
    at t (http://localhost:1234/modelujeme/sluzby/auth-server/resources/9ds4a/common/keycloak/node_modules/jquery/dist/jquery.min.js:2:30307) undefined
S.Deferred.exceptionHook @ jquery.min.js:2
t @ jquery.min.js:2`

`jquery.min.js:2 Uncaught ReferenceError: Keycloak is not defined
    at HTMLDocument.<anonymous> (localhost:1234/modelujeme/sluzby/auth-server/resources/9ds4a/admin/keycloak/js/app.js:14:24)
    at e (localhost:1234/modelujeme/sluzby/auth-server/resources/9ds4a/common/keycloak/node_modules/jquery/dist/jquery.min.js:2:30005)
    at t (localhost:1234/modelujeme/sluzby/auth-server/resources/9ds4a/common/keycloak/node_modules/jquery/dist/jquery.min.js:2:30307)
(anonymní) @ app.js:14
e @ jquery.min.js:2
t @ jquery.min.js:2`

V konfiguračních souborech nikde odkaz na https://xn--slovnk-7va.dev či podobné adresy nevidím, tak nevím, jak to upravit sama.

# Závažnost problému
Mezi 3. a 4., spíše 4. příliš mojí práci neovlivňuje.

**Comment by MichalMed** [comment]
Ideální by bylo, kdyby to aktualizoval někdo, kdo to v poslední době nasazoval - @blcham ?

**Comment by blcham** [comment]
Suhlas, aktualizuji.

**Comment by blcham** [comment]
@bindeali Takto uz funguje ?
https://github.com/opendata-mvcr/sgov-assembly-line/pull/94

Jestli ano prosim zavri ticket.

**Comment by bindeali** [comment]
Díky - funguje, zavírám.
